# fisier arhivat, astea sunt cartile inainte de db


books = [
    {
        "id": 1,
        "title": "Think Python",
        "author": "Allen B. Downey",
        "publisher": "O'Reilly Media",
        "published_date": "2021-01-01",
        "page_count": 1234,
        "language": "English",
    },
    {
        "id": 2,
        "title": "Django By Example",
        "author": "Antonio Mele",
        "publisher": "Packt Publishing Ltd",
        "published_date": "2022-01-19",
        "page_count": 1023,
        "language": "English",
    },
    {
        "id": 3,
        "title": "Clean Code",
        "author": "Robert C. Martin",
        "publisher": "Prentice Hall",
        "published_date": "2008-08-11",
        "page_count": 464,
        "language": "English",
    },
    {
        "id": 4,
        "title": "Fluent Python",
        "author": "Luciano Ramalho",
        "publisher": "O'Reilly Media",
        "published_date": "2022-04-01",
        "page_count": 1012,
        "language": "English",
    },
    {
        "id": 5,
        "title": "The Pragmatic Programmer",
        "author": "David Thomas",
        "publisher": "Addison-Wesley",
        "published_date": "2019-09-13",
        "page_count": 352,
        "language": "English",
    },
    {
        "id": 6,
        "title": "Python Crash Course",
        "author": "Eric Matthes",
        "publisher": "No Starch Press",
        "published_date": "2023-01-10",
        "page_count": 552,
        "language": "English",
    },
    {
        "id": 7,
        "title": "Automate the Boring Stuff with Python",
        "author": "Al Sweigart",
        "publisher": "No Starch Press",
        "published_date": "2020-11-12",
        "page_count": 592,
        "language": "English",
    },
]